In [2]:
import pandas as pd
import numpy as np
import re
import nltk

In [3]:
dataset = pd.read_csv("Restaurant_Reviews.tsv", delimiter="\t")

In [4]:
dataset.drop("Liked", axis=1, inplace=True)

In [5]:
dataset

Review
0                             Wow... Loved this place.
1                                   Crust is not good.
2            Not tasty and the texture was just nasty.
3    Stopped by during the late May bank holiday of...
4    The selection on the menu was great and so wer...
..                                                 ...
995  I think food should have flavor and texture an...
996                           Appetite instantly gone.
997  Overall I was not impressed and would not go b...
998  The whole experience was underwhelming, and I ...
999  Then, as if I hadn't wasted enough of my life ...

[1000 rows x 1 columns]

In [6]:
corpus=[]
for i in range(1000):
    review=dataset["Review"][i]
    review = re.sub("[^a-zA-Z]"," ",review)
    review = review.lower()
    corpus.append(review)

In [7]:
corpus

['wow    loved this place ',
 'crust is not good ',
 'not tasty and the texture was just nasty ',
 'stopped by during the late may bank holiday off rick steve recommendation and loved it ',
 'the selection on the menu was great and so were the prices ',
 'now i am getting angry and i want my damn pho ',
 'honeslty it didn t taste that fresh  ',
 'the potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer ',
 'the fries were great too ',
 'a great touch ',
 'service was very prompt ',
 'would not go back ',
 'the cashier had no care what so ever on what i had to say it still ended up being wayyy overpriced ',
 'i tried the cape cod ravoli  chicken  with cranberry   mmmm ',
 'i was disgusted because i was pretty sure that was human hair ',
 'i was shocked because no signs indicate cash only ',
 'highly recommended ',
 'waitress was a little slow in service ',
 'this place is not worth your time  let alone vegas ',
 'did not like at all 

In [8]:
from keras.preprocessing.text import Tokenizer

In [9]:
tokenizer = Tokenizer()

In [10]:
tokenizer.fit_on_texts(corpus)

In [11]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'i': 3,
 'was': 4,
 'a': 5,
 'to': 6,
 'is': 7,
 'it': 8,
 'this': 9,
 'of': 10,
 'food': 11,
 'not': 12,
 'for': 13,
 'in': 14,
 'place': 15,
 't': 16,
 'good': 17,
 'we': 18,
 'service': 19,
 'very': 20,
 'my': 21,
 'with': 22,
 'great': 23,
 'had': 24,
 'that': 25,
 'be': 26,
 'so': 27,
 'you': 28,
 'were': 29,
 'are': 30,
 'but': 31,
 'have': 32,
 'back': 33,
 'they': 34,
 'here': 35,
 'on': 36,
 'at': 37,
 'like': 38,
 'go': 39,
 'all': 40,
 'time': 41,
 's': 42,
 'our': 43,
 'will': 44,
 'there': 45,
 'as': 46,
 'really': 47,
 'just': 48,
 'an': 49,
 'their': 50,
 'if': 51,
 'best': 52,
 'would': 53,
 'ever': 54,
 'also': 55,
 'friendly': 56,
 'up': 57,
 'only': 58,
 'never': 59,
 'one': 60,
 'don': 61,
 'no': 62,
 'your': 63,
 'restaurant': 64,
 'out': 65,
 'nice': 66,
 'been': 67,
 'what': 68,
 'amazing': 69,
 'again': 70,
 'can': 71,
 'from': 72,
 'delicious': 73,
 've': 74,
 'vegas': 75,
 'did': 76,
 'by': 77,
 'which': 78,
 'm': 79,
 'pretty': 80,
 'so

In [12]:
token_list = tokenizer.texts_to_sequences(corpus)

In [13]:
token_list

[[421, 167, 9, 15],
 [578, 7, 12, 17],
 [12, 153, 2, 1, 422, 4, 48, 423],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882, 883, 424, 2, 167, 8],
 [1, 168, 36, 1, 111, 4, 23, 2, 27, 29, 1, 169],
 [142, 3, 260, 202, 884, 2, 3, 132, 21, 346, 261],
 [885, 8, 133, 16, 134, 25, 123],
 [1,
  425,
  29,
  38,
  886,
  2,
  28,
  107,
  262,
  34,
  24,
  67,
  102,
  57,
  887,
  10,
  41,
  124,
  293,
  426,
  5,
  888],
 [1, 183, 29, 23, 112],
 [5, 23, 581],
 [19, 4, 20, 889],
 [53, 12, 39, 33],
 [1,
  582,
  24,
  62,
  427,
  68,
  27,
  54,
  36,
  68,
  3,
  24,
  6,
  108,
  8,
  154,
  583,
  57,
  124,
  890,
  233],
 [3, 234, 1, 891, 892, 893, 103, 22, 894, 584],
 [3, 4, 895, 125, 3, 4, 80, 203, 25, 4, 585, 586],
 [3, 4, 896, 125, 62, 897, 898, 899, 58],
 [347, 428],
 [204, 4, 5, 170, 155, 14, 19],
 [9, 15, 7, 12, 171, 63, 41, 429, 900, 75],
 [76, 12, 38, 37, 40],
 [1, 901, 902],
 [1, 11, 69],
 [19, 7, 55, 587],
 [3, 107, 427, 903, 1, 904, 7, 48, 430],
 [27, 34, 905],
 [25, 42, 184,

In [14]:
input_sequences=[]

In [15]:
for review in corpus:
    token_list = tokenizer.texts_to_sequences([review])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [16]:
input_sequences

[[421, 167],
 [421, 167, 9],
 [421, 167, 9, 15],
 [578, 7],
 [578, 7, 12],
 [578, 7, 12, 17],
 [12, 153],
 [12, 153, 2],
 [12, 153, 2, 1],
 [12, 153, 2, 1, 422],
 [12, 153, 2, 1, 422, 4],
 [12, 153, 2, 1, 422, 4, 48],
 [12, 153, 2, 1, 422, 4, 48, 423],
 [579, 77],
 [579, 77, 291],
 [579, 77, 291, 1],
 [579, 77, 291, 1, 580],
 [579, 77, 291, 1, 580, 292],
 [579, 77, 291, 1, 580, 292, 880],
 [579, 77, 291, 1, 580, 292, 880, 881],
 [579, 77, 291, 1, 580, 292, 880, 881, 182],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882, 883],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882, 883, 424],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882, 883, 424, 2],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882, 883, 424, 2, 167],
 [579, 77, 291, 1, 580, 292, 880, 881, 182, 882, 883, 424, 2, 167, 8],
 [1, 168],
 [1, 168, 36],
 [1, 168, 36, 1],
 [1, 168, 36, 1, 111],
 [1, 168, 36, 1, 111, 4],
 [1, 168, 36, 1, 111, 4, 23],
 [1, 168, 36, 1, 111, 4, 23, 2],


In [17]:
max_sequence_len = max([len(x) for x in input_sequences])

In [18]:
max_sequence_len

32

In [18]:
from keras.preprocessing.sequence import pad_sequences

In [19]:
input_sequences=pad_sequences(input_sequences,max_sequence_len,padding="pre")

In [20]:
input_sequences.shape

(10040, 32)

In [21]:
x=input_sequences[:,:-1]

In [22]:
y=input_sequences[:,-1]

In [23]:
x

array([[  0,   0,   0, ...,   0,   0, 421],
       [  0,   0,   0, ...,   0, 421, 167],
       [  0,   0,   0, ..., 421, 167,   9],
       ...,
       [  0,   0,   0, ...,   8, 205,   6],
       [  0,   0,   0, ..., 205,   6, 343],
       [  0,   0,   0, ...,   6, 343,   1]])

In [24]:
y

array([167,   9,  15, ..., 343,   1, 248])

In [25]:
import keras

In [26]:
y=keras.utils.to_categorical(y,num_classes=2023)

In [27]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

(10040, 31)

In [34]:
from keras.layers import Embedding

In [35]:
from keras.models import Sequential


# Init NN model

In [38]:
total_words=2023

In [39]:
model=Sequential()

In [40]:
model.add(Embedding(input_dim=total_words,output_dim=15,input_length=max_sequence_len-1))

In [41]:
model.compile(optimizer='adam',loss='mse')

In [44]:
x[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0, 421])

In [46]:
model.predict(x)[0]

array([[-0.04402339, -0.03888506,  0.04867407, -0.01627153, -0.01692342,
        -0.01607239, -0.01059046,  0.02662964, -0.04288392, -0.00851561,
        -0.02312268,  0.03702495,  0.04939956,  0.02366075, -0.03121018],
       [-0.04402339, -0.03888506,  0.04867407, -0.01627153, -0.01692342,
        -0.01607239, -0.01059046,  0.02662964, -0.04288392, -0.00851561,
        -0.02312268,  0.03702495,  0.04939956,  0.02366075, -0.03121018],
       [-0.04402339, -0.03888506,  0.04867407, -0.01627153, -0.01692342,
        -0.01607239, -0.01059046,  0.02662964, -0.04288392, -0.00851561,
        -0.02312268,  0.03702495,  0.04939956,  0.02366075, -0.03121018],
       [-0.04402339, -0.03888506,  0.04867407, -0.01627153, -0.01692342,
        -0.01607239, -0.01059046,  0.02662964, -0.04288392, -0.00851561,
        -0.02312268,  0.03702495,  0.04939956,  0.02366075, -0.03121018],
       [-0.04402339, -0.03888506,  0.04867407, -0.01627153, -0.01692342,
        -0.01607239, -0.01059046,  0.02662964, 

In [47]:
x[0].shape

(31,)

In [48]:
model.predict(x)[0].shape

(31, 15)

# INIT NN model

In [49]:
model1=Sequential()

In [50]:
from keras.layers import LSTM

In [57]:
from keras.layers import Dense

In [51]:
total_words=2023

In [53]:
model1.add(Embedding(input_dim=total_words,output_dim=15,input_length=31))

In [54]:
model1.add(LSTM(return_sequences=True,units=200,kernel_initializer='glorot_uniform'))

In [55]:
model1.add(LSTM(return_sequences=True,units=100,kernel_initializer='glorot_uniform'))

In [56]:
model1.add(LSTM(return_sequences=False,units=100,kernel_initializer='glorot_uniform'))


# output layers

In [58]:
model1.add(Dense(kernel_initializer='glorot_uniform',activation='softmax',units=total_words))

In [61]:
model1.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [62]:
model1.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 31, 15)            30345     
_________________________________________________________________
lstm_1 (LSTM)                (None, 31, 200)           172800    
_________________________________________________________________
lstm_2 (LSTM)                (None, 31, 100)           120400    
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_1 (Dense)              (None, 2023)              204323    
Total params: 608,268
Trainable params: 608,268
Non-trainable params: 0
_________________________________________________________________


In [63]:
# train and test divide based on iloc like time series

In [64]:
model1.fit(x,y,epochs=200,batch_size=32)

C:\Users\errisam\anaconda3\lib\site-packages\tensorflow\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(


Epoch 1/200
10040/10040 [==============================] - 37s 4ms/step - loss: 6.5386 - accuracy: 0.0381
Epoch 2/200
10040/10040 [==============================] - 33s 3ms/step - loss: 6.2198 - accuracy: 0.0384
Epoch 3/200
10040/10040 [==============================] - 33s 3ms/step - loss: 6.1560 - accuracy: 0.0391
Epoch 4/200
10040/10040 [==============================] - 33s 3ms/step - loss: 6.0371 - accuracy: 0.0473
Epoch 5/200
10040/10040 [==============================] - 33s 3ms/step - loss: 5.9327 - accuracy: 0.0571
Epoch 6/200
10040/10040 [==============================] - 34s 3ms/step - loss: 5.8202 - accuracy: 0.0671
Epoch 7/200
10040/10040 [==============================] - 36s 4ms/step - loss: 5.7085 - accuracy: 0.0745
Epoch 8/200
10040/10040 [==============================] - 35s 3ms/step - loss: 5.5939 - accuracy: 0.0827
Epoch 9/200
10040/10040 [==============================] - 33s 3ms/step - loss: 5.4939 - accuracy: 0.0907
Epoch 10/200
10040/10040 [====================

10040/10040 [==============================] - 33s 3ms/step - loss: 1.1823 - accuracy: 0.7400
Epoch 154/200
10040/10040 [==============================] - 32s 3ms/step - loss: 1.1716 - accuracy: 0.7391
Epoch 155/200
10040/10040 [==============================] - 32s 3ms/step - loss: 1.1574 - accuracy: 0.7400
Epoch 156/200
10040/10040 [==============================] - 33s 3ms/step - loss: 1.1434 - accuracy: 0.7459
Epoch 157/200
10040/10040 [==============================] - 32s 3ms/step - loss: 1.1414 - accuracy: 0.7451
Epoch 158/200
10040/10040 [==============================] - 32s 3ms/step - loss: 1.1345 - accuracy: 0.7470
Epoch 159/200
10040/10040 [==============================] - 33s 3ms/step - loss: 1.1169 - accuracy: 0.7516
Epoch 160/200
10040/10040 [==============================] - 33s 3ms/step - loss: 1.1062 - accuracy: 0.7562
Epoch 161/200
10040/10040 [==============================] - 32s 3ms/step - loss: 1.0935 - accuracy: 0.7572
Epoch 162/200
10040/10040 [===============

In [65]:
model.save('next_word_prediction.h5')
import joblib
joblib.dump(tokenizer,'tokemizer_next_word.pkl')

['tokemizer_next_word.pkl']

In [ ]:
# to solve overfitting
#CountVectorizer(max_features=1500)
# n gram
